apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "bof_tmp_project.fullname" . }}-clusterrolebinding
  labels:
    {{- include "bof_tmp_project.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "bof_tmp_project.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "bof_tmp_project.fullname" . }}-clusterrole
  apiGroup: rbac.authorization.k8s.io