apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bof_tmp_project.fullname" . }}-controller
  labels:
    {{- include "bof_tmp_project.controller.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "bof_tmp_project.controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bof_tmp_project.controller.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bof_tmp_project.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: IfNotPresent
        command: ["python", "main.py", "run", "-A"]
        {{- with .Values.controller.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.controller.env }}
        env:
          {{- toYaml . | nindent 10 }}
        {{- end }}
