apiVersion: v1
kind: Service
metadata:
  name: {{ include "bof_tmp_project.fullname" . }}-webhook-service
  labels:
    {{- include "bof_tmp_project.webhook.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: {{ .Values.webhook.port }}
  selector:
    {{- include "bof_tmp_project.webhook.selectorLabels" . | nindent 4 }}
